version: "3.7"

services:
    database:
        build:
            context: ./postgres
            dockerfile: Dockerfile
        restart: always
        networks:
            - iot-intra
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: iot-server
        # ports:
        #     - "2345:5432"
        volumes:
            - ./volumes/database:/var/lib/postgresql/data
    iot-server:
        build:
            context: ./express
            dockerfile: Dockerfile
        restart: always
        networks:
          - iot-intra
          - iot-web
        ports:
            - "9919:3000"
        environment:
            PGUSER: admin
            PGHOST: database
            PGPASSWORD: postgres
            PGDATABASE: iot-server
            PGPORT: 5432
        volumes:
            - ./volumes/wifimapper:/var/www/html

    mosquitto:
        image: eclipse-mosquitto
        network_mode: host
        volumes:
          - ./conf:/mosquitto/conf
          - ./data:/mosquitto/data
          - ./log:/mosquitto/log
        ports:
          - 1883:1883
          - 9001:9001

networks:
    iot-web:
        external: true
    iot-intra:
        external: false